Add slider for time in animation controller
nest-desktop/nest-desktop pull request #175
Opened 2021-12-07 13:56 UTC by babsey

This PR adds time slider for animation controller.

2021-12-07 13:57 UTC, babsey commented
![screenshot-localhost_8001-2021 12 07-14_57_11](https://user-images.githubusercontent.com/620984/145042278-6d1519f7-e1c3-4ea4-9827-6dba08807d31.png)

2021-12-10 21:03 UTC, jens-br requested changes
Small adjustments suggested. I added a PR with also a visual improvement in your fork.

2021-12-10 21:42 UTC, jens-br commented on src/components/parameter/ParameterEdit.vue
> +                          :large="state.options.iconSize != null ? false : true"
My bad -as suggested, this should be a bit better:

```suggestion
                          :small="state.options.iconSize === 'small'"
                          :large="state.options.iconSize === 'large'"
```

2021-12-13 10:42 UTC, jens-br approved these changes
LGTM :+1:

2021-12-13 10:43 UTC, merged