Clean node modules
nest-desktop/nest-desktop pull request #223
Opened 2022-01-14 11:47 UTC by babsey

This PR cleans node modules and re-initialize unit tests.

2022-01-14 19:37 UTC, jens-br requested changes
Looks good, however, `electron:test` seems to fail. 
```
  [=========================] 100% (completed)

 WEBPACK  Compiled successfully in 15307ms

 MOCHA  Testing...



  Application launch
    1) "before each" hook for "opens a window"


  0 passing (30s)
  1 failing

  1) Application launch
       "before each" hook for "opens a window":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
Could you re-check that?

2022-01-17 07:49 UTC, babsey commented
Can you delete the folder `node_modules`, reinstall modules and test it again? 
Mostly it works again after correct installation.

2022-01-17 11:42 UTC, jens-br commented
It does not (with a different error), but since it seems to be an issue related to Vue CLI and Webpack, we should have a look at it when the new version of Vue CLI is released.

2022-01-17 11:43 UTC, jens-br approved these changes

2022-01-17 11:43 UTC, merged