[Big Bang] Code template
nest-desktop/nest-desktop pull request #317
Opened 2022-03-08 12:40 UTC by babsey

This PR adds templates for simulation code.

It also uses getter for all is[A-Z].* and has[A-Z].* functions.

2022-03-16 19:03 UTC, jens-br requested changes
Good additions! I have some suggestions below.

It could also be helpful to refactor the methods `get someParams()` (e.g. to `get hasParams()`) to use a more intuitive name (used in `connection.ts`, `node.ts` and `synapse.ts`).

2022-03-16 20:37 UTC, jens-br commented
(renamed to improve the readability of the Git logs and the change list for new versions)

2022-03-17 07:12 UTC, babsey commented on src/core/simulation/simulationCode.ts
> +  private _state: UnwrapRef<any>;
Nice!

2022-03-17 07:17 UTC, babsey commented on src/components/model/ModelExplorer.vue
>        v-if="modelView.state.project"
Strange! I cannot reproduce some error showing this notification.

2022-03-17 14:55 UTC, jens-br commented on src/components/model/ModelExplorer.vue
>        v-if="modelView.state.project"
It is a message in VS Code. We can leave it for now and have a look on it later on.

2022-03-17 14:56 UTC, jens-br approved these changes
LGTM :+1:

2022-03-17 14:56 UTC, merged