Docs: Use headings
nest-desktop/nest-desktop pull request #330
Opened 2022-03-17 21:58 UTC by jens-br

This PR is a suggestion and uses headings instead of bold text in order to optimize the usability (user can reference single sections by himself easily).

This PR is based on #329 .

2022-03-22 13:51 UTC, babsey requested changes
LGTM except small suggestions to add empty line after header

2022-03-22 13:51 UTC, babsey commented on docs/deployer/deploy-docker-compose.rst
> +Prepare your local environment by installing Docker (if you have not installed it yet).
Add empty line

2022-03-22 13:51 UTC, babsey commented on docs/deployer/deploy-docker-compose.rst
> +The configuration file  `docker-compose.yml` contains all setup steps executed by Docker.
Add empty line.

2022-03-22 13:51 UTC, babsey commented on docs/user/nest-models.rst
> +It is possible to select filter tags to display only models with certain properties.
Add empty line.

2022-03-25 13:34 UTC, jens-br commented on docs/deployer/deploy-docker-compose.rst
> +Prepare your local environment by installing Docker (if you have not installed it yet).
Please see [9e88a45](https://github.com/nest-desktop/nest-desktop/pull/330/commits/9e88a459b953571b9dec3c366abf3f0e44757891)

2022-03-25 13:34 UTC, jens-br commented on docs/deployer/deploy-docker-compose.rst
> +The configuration file  `docker-compose.yml` contains all setup steps executed by Docker.
Please see [9e88a45](https://github.com/nest-desktop/nest-desktop/pull/330/commits/9e88a459b953571b9dec3c366abf3f0e44757891)

2022-03-25 13:34 UTC, jens-br commented on docs/user/nest-models.rst
> +It is possible to select filter tags to display only models with certain properties.
Please see [9e88a45](https://github.com/nest-desktop/nest-desktop/pull/330/commits/9e88a459b953571b9dec3c366abf3f0e44757891)

2022-03-25 13:34 UTC, babsey approved these changes
LGTM!

2022-03-25 13:35 UTC, merged