Upgrade doc
nest-desktop/nest-desktop pull request #447
Opened 2022-11-22 10:43 UTC by babsey

Upgrade doc for v3.2

2023-02-17 14:50 UTC, jens-br requested changes
Those are nice additions! I would suggest to inlcude some changes.

As a general aspect, we could think of some structural changes to the usage guides and the reference section - in the future.

2023-02-22 09:01 UTC, babsey commented on docs/about/events.rst
> +:26 - 28 Apr: MSc course "Biophysics of Neurons and Networks" at BCF [#f1]_, Freiburg, Germany.
Indeed, the footnote link is not good styled.
The style of sphinx material conflicts with bootstrap css.

2023-02-22 09:46 UTC, babsey commented on docs/about/index.rst
> +.. include:: abstract.rst
Be honest, I do not like the iframe of the live-demo. 
Instead, I prefer using link to open a live-demo in a new tab.

2023-02-22 09:46 UTC, babsey commented on docs/developer/coding-conventions.rst
> +  and for Python (|see| `PEP 8 <https://www.python.org/dev/peps/pep-0008/>`__) should be followed.
Fixed.

2023-02-22 09:47 UTC, babsey commented on docs/lecturer/master/network-dynamics.rst
> +      (|see| https://www.nest-simulator.org/connection-management).
Fixed

2023-02-22 09:50 UTC, babsey commented on docs/user/setup/snap.rst
> +   snap install nest-desktop
Yeah, I am aware of it. Tried several times. We can create an issue of it, with low priority.

2023-02-22 10:09 UTC, babsey commented on docs/troubleshootings/error.rst
> +  |see| the :doc:`FAQ for NEST Simulator </troubleshootings/nest-simulator>`.
fixed.

2023-02-22 11:52 UTC, babsey commented on docs/lecturer/bachelor/single-neuron-poisson-input.rst
For now, we can ignore these warnings.

2023-02-22 16:18 UTC, jens-br commented on docs/user/setup/appimage.rst
> +AppImage |linux|
Let's address it in an issue (#524 ).

2023-02-22 16:18 UTC, jens-br commented on docs/user/setup/apptainer.rst
> +Apptainer |linux|
(#524 )

2023-02-22 16:18 UTC, jens-br commented on docs/user/setup/docker-compose.rst
> +Docker Compose |linux| |windows| |apple|
(#524 )

2023-02-22 16:18 UTC, jens-br commented on docs/user/setup/conda.rst
> +Conda |linux| |windows| |apple|
(#524)

2023-02-22 16:19 UTC, jens-br commented on docs/user/setup/docker-compose.rst
> +Windows |windows| and macOS |apple|
(#524)

2023-02-22 16:19 UTC, jens-br commented on docs/lecturer/bachelor/single-neuron-poisson-input.rst
We will track it in #524 .

2023-02-22 16:25 UTC, jens-br approved these changes
LGTM :+1:

2023-02-22 16:25 UTC, merged