Update events in doc
nest-desktop/nest-desktop pull request #526
Opened 2023-02-24 09:24 UTC by babsey

2023-02-24 15:24 UTC, jens-br requested changes
Seems good, except for one line.

2023-02-24 15:24 UTC, jens-br commented on docs/about/events.rst
> +:18 - 20 Jan: Poster at `7th HBP Student Conference <https://www.humanbrainproject.eu/en/education-training-career/HBPSC2023/>`, Madrid, Spain (cancelled).
I do have first-hand information that it was not cancelled!!! :joy: 
```suggestion
:18 - 20 Jan: Poster at `7th HBP Student Conference <https://www.humanbrainproject.eu/en/education-training-career/HBPSC2023/>`__, Madrid, Spain.
```

2023-02-24 15:30 UTC, jens-br requested changes
*two lines, sry

2023-02-24 15:30 UTC, jens-br commented on docs/about/events.rst
> +:03 - 09 Jul: Part of the workshop "NEST Workshop: network and plasticity" at `9th BNNI <http://bionn.matinf.uj.edu.pl/events/bnni2022/#program>`, presented by Jasper Albers, Krakau, Poland.
```suggestion
:03 - 09 Jul: Part of the workshop "NEST Workshop: network and plasticity" at `9th BNNI <http://bionn.matinf.uj.edu.pl/events/bnni2022/#program>`__, presented by Jasper Albers, Krakau, Poland.
```

2023-02-27 11:38 UTC, babsey commented
We will come back to this style issue later.

2023-02-27 12:52 UTC, jens-br approved these changes
LGTM :+1:

2023-02-27 12:52 UTC, merged