Restructure code files and smaller buttons in menu
nest-desktop/nest-desktop pull request #92
Opened 2021-07-04 12:24 UTC by babsey

This PR restructures components of nodes and connections.

It adds parameter editing in menu.
I also reduced the size of the menu buttons in menu.

2021-07-07 13:31 UTC, jens-br requested changes
When I click on a node, I receive the error
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <NetworkNodeChip> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <NetworkGraphToolbar> at src/components/network/NetworkGraphToolbar.vue
       <NetworkGraph> at src/components/network/NetworkGraph.vue
         <VMain>
           <Project> at src/views/Project.vue
             <VApp>
               <App> at src/App.vue
                 <Root>
```
I think we need to change in `NetworkGraphToolbar.vue` the lines  mentioned in the comment. An alternative would be to change ` NetworkNodeChip`  to export ` NodeChip` , if that was intended.

I think I liked "NetworkParamsEdit", since it indicated the editing of multiple parameters.

2021-07-07 13:31 UTC, jens-br commented on src/core/connection/connection.ts
> +   * Sets default param value.
```suggestion
   * Resets all parameters to their default value.
```

2021-07-08 09:37 UTC, babsey commented
I changed the component name to NodeChip and updated the description for the function in connection.ts

2021-07-08 14:21 UTC, jens-br approved these changes
LGTM

2021-07-08 14:21 UTC, merged